function TablaYerbas() {
    const ContenedorYerbas = [
    {index: 1, nombre: 'Canarias tradicional', marca: 'Canarias', tipo: 'Tradicional', tipoMolienda: 'Sin palo', imagen: 'canarias-removebg-preview.png' },
    {index: 2, nombre: 'Baldo tradicional', marca: 'Baldo', tipo: 'Tradicional', tipoMolienda: 'Sin palo', imagen: 'baldo-removebg-preview.png' },
    {index: 3, nombre: 'Canarias especial', marca: 'Canarias', tipo: 'Especial', tipoMolienda: 'Sin palo', imagen: 'canariasEspecial-removebg-preview.png' },
    {index: 4, nombre: 'Canarias serena', marca: 'Canarias', tipo: 'Hierbas', tipoMolienda: 'Sin palo', imagen: 'canariasSerena-removebg-preview.png' },
    {index: 5, nombre: 'Canarias te rojo y centella', marca: 'Canarias', tipo: 'Hierbas', tipoMolienda: 'Sin palo', imagen: 'canariasTeRojoCentella-removebg-preview.png' },
    {index: 6, nombre: 'Contigo tradicional', marca: 'Contigo', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'contigo-1-removebg-preview.png' },
    {index: 7, nombre: 'contigo con hierbas', marca: 'Contigo', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'contigoConHierbas-removebg-preview.png' },
    {index: 8, nombre: 'La Merced de monte', marca: 'La Merced', tipo: 'Monte', tipoMolienda: 'Con palo', imagen: 'mercedDeMonte-removebg-preview.png' },
    {index: 9, nombre: 'Union tradicional', marca: 'Union', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'unionOriginal-removebg-preview.png' },
    {index: 10, nombre: 'Playadito hierbas', marca: 'Playadito', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'playaditoHierbas-removebg-preview.png' },
    {index: 11, nombre: 'Andresito tradicional', marca: 'Adresito', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'andresito-removebg-preview.png' },
    {index: 12, nombre: 'Kalena despalada', marca: 'Kalena', tipo: 'Despalada', tipoMolienda: 'Sin palo', imagen: 'kalenaDespalada-removebg-preview.png' },
    {index: 13, nombre: 'La Merced campo y monte', marca: 'La Merced', tipo: 'Campo y Monte', tipoMolienda: 'Con palo', imagen: 'mercedCampoMonte-removebg-preview.png' },
    {index: 14, nombre: 'Titrayju tradicional', tipo: 'Tradicional', marca: 'Titrayju', tipoMolienda: 'Con palo', imagen: 'titraiju-removebg-preview.png' },
    {index: 15, nombre: 'La Tranquera especial', marca: 'La Tranquera', tipo: 'Especial', tipoMolienda: 'Con palo', imagen: 'tranqueraSeleccionEspecial-removebg-preview.png' },
    {index: 16, nombre: 'Nobleza gaucha especial', marca: 'Nombleza gaucha', tipo: 'Especial', tipoMolienda: 'Con palo', imagen: 'noblezaGauchaSeleccion-removebg-preview.png' },
    {index: 17, nombre: 'Amanda especial', marca: 'Amanda', tipo: 'Especial', tipoMolienda: 'Con palo', imagen: 'amandaEspecial-removebg-preview.png' },
    {index: 18, nombre: 'Taragui despalada', marca: 'Taragui', tipo: 'Despalada', tipoMolienda: 'Sin palo', imagen: 'taraguiDespalada-removebg-preview.png' },
    {index: 19, nombre: 'Rosa monte especial', marca: 'Rosa monte', tipo: 'Especial', tipoMolienda: 'Con palo', imagen: 'rosaMonteSeleccion-removebg-preview.png' },
    {index: 20, nombre: 'Cruz de malta especial', marca: 'Cruz de malta', tipo: 'Especial', tipoMolienda: 'Con palo', imagen: 'cruzDeMaltaSeleccion-removebg-preview.png' },
    {index: 21, nombre: 'La Merced barbacua', marca: 'La Merced', tipo: 'Barbacua', tipoMolienda: 'Con palo', imagen: 'mercedBarbacua-removebg-preview.png' },
    {index: 22, nombre: 'Amanda tradicional', marca: 'Amanda', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'amanda-removebg-preview.png' },
    {index: 23, nombre: 'Amanda premium', marca: 'Amanda', tipo: 'Premium', tipoMolienda: 'Con palo', imagen: 'amandaPremium-removebg-preview.png' },
    {index: 24, nombre: 'Porongo tradicional', marca: 'Porongo', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'porongo-removebg-preview.png' },
    {index: 25, nombre: 'Playadito despalada', marca: 'Playadito', tipo: 'Despalada', tipoMolienda: 'Sin palo', imagen: 'playaditoDespalada-removebg-preview.png' },
    {index: 26, nombre: 'Playadito tradicional', marca: 'Playadito', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'playadito-removebg-preview.png' },
    {index: 27, nombre: 'Nobleza gaucha suave', marca: 'Nobleza gaucha', tipo: 'Suave', tipoMolienda: 'Con palo', imagen: 'noblezaGauchaSuave-removebg-preview.png' },
    {index: 28, nombre: 'Romance especial', marca: 'Romance', tipo: 'Especial', tipoMolienda: 'Con palo', imagen: 'romanceSeleccion-removebg-preview.png' },
    {index: 29, nombre: 'Amanda naranja', marca: 'Amanda', tipo: 'Saborizantes', tipoMolienda: 'Con palo', imagen: 'amandaNaranja-removebg-preview.png' },
    {index: 30, nombre: 'Amanda hierbas', marca: 'Amanda', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'amandaHierbas-removebg-preview.png' },
    {index: 31, nombre: 'La Merced campo', marca: 'La Merced', tipo: 'Campo', tipoMolienda: 'Con palo', imagen: 'mercedCampo-removebg-preview.png' },
    {index: 32, nombre: 'Mañanita tradicional', marca: 'Mañanita', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'mañanita-removebg-preview.png' },
    {index: 33, nombre: 'Aguantadora tradicional', marca: 'Aguantadora', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'aguantadora-removebg-preview.png' },
    {index: 34, nombre: 'Amanda limon', marca: 'Amanda', tipo: 'Saborizante', tipoMolienda: 'Con palo', imagen: 'amandaLimon-removebg-preview.png' },
    {index: 35, nombre: 'Amanda despalada', marca: 'Amanda', tipo: 'Despalada', tipoMolienda: 'Sin palo', imagen: 'amandaDespalada-removebg-preview.png' },
    {index: 36, nombre: 'Kalena tradicional', marca: 'Kalena', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'kalena-removebg-preview.png' },
    {index: 37, nombre: 'Cruz de malta tradicional', marca: 'Cruz de malta', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'cruzDeMalta-removebg-preview.png' },
    {index: 38, nombre: 'Amanda hierbas serranas', marca: 'Amanda', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'amandaHierbasSerranas-removebg-preview.png' },
    {index: 39, nombre: 'Taragui tradicional', marca: 'Taragui', tipo: 'Despalada', tipoMolienda: 'Con palo', imagen: 'taragui-removebg-preview.png' },
    {index: 40, nombre: 'Aguantadora suave', marca: 'Aguantadora', tipo: 'Suave', tipoMolienda: 'Con palo', imagen: 'aguantadoraSuave-removebg-preview.png' },
    {index: 41, nombre: 'Rosa monte tradicional', marca: 'Rosa monte', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'rosaMonte-removebg-preview.png' },
    {index: 42, nombre: 'Rosa monte despalada', marca: 'Rosa monte', tipo: 'Despalada', tipoMolienda: 'Sin palo', imagen: 'rosaMonteDespalada-removebg-preview.png' },
    {index: 43, nombre: 'Pipore tradicional', marca: 'Pipore', tipo: 'Tradicional', tipoMolienda: 'Con palo', imagen: 'pipore-removebg-preview.png' },
    {index: 44, nombre: 'Pipore suave', marca: 'Pipore', tipo: 'Suave', tipoMolienda: 'Con palo', imagen: 'piporeSuave-removebg-preview.png' },
    {index: 45, nombre: 'Pipore despalada', marca: 'Pipore', tipo: 'Despalada', tipoMolienda: 'Sin palo', imagen: 'piporeDespalada-removebg-preview.png' },
    {index: 46, nombre: 'CBSE naranja', marca: 'CBSE', tipo: 'Saborizante', tipoMolienda: 'Con palo', imagen: 'cbseNaranja-removebg-preview.png' },
    {index: 47, nombre: 'CBSE hierbas serranas', marca: 'CBSE', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'cbseHierbasSerranas-removebg-preview.png' },
    {index: 48, nombre: 'CBSE hierbas litoral', marca: 'CBSE', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'cbseHierbasLitoral-removebg-preview.png' },
    {index: 49, nombre: 'CBSE endulife', marca: 'CBSE', tipo: 'Saborizante', tipoMolienda: 'Con palo', imagen: 'cbseEndulife-removebg-preview.png' },
    {index: 50, nombre: 'CBSE pomelo', marca: 'CBSE', tipo: 'Saborizante', tipoMolienda: 'Con palo', imagen: 'cbsePomelo-removebg-preview.png' },
    {index: 51, nombre: 'CBSE frutos del bosque', marca: 'CBSE', tipo: 'Saborizante', tipoMolienda: 'Con palo', imagenes: 'cbseFrutosDelBosque-removebg-preview.png' },
    {index: 52, nombre: 'CBSE limon', marca: 'CBSE', tipo: 'Saborizante', tipoMolienda: 'Con palo', imagen: 'cbseLimon-removebg-preview.png' },
    {index: 53, nombre: 'CBSE guarana', marca: 'CBSE', tipo: 'Saborizante', tipoMolienda: 'Con palo', imagen: 'cbseGuarana-removebg-preview.png' },
    {index: 54, nombre: 'Cachamate hierbas', marca: 'Cachamate', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'cachamateHierbas-removebg-preview.png' },
    {index: 55, nombre: 'Cachamate hierbas digestivas', marca: 'Cachamate', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'cachamateHierbasDigestivas-removebg-preview.png' },
    {index: 56, nombre: 'Cachamate hierbas pampeanas', marca: 'Cachamate', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'cachamateHierbasPampeanas-removebg-preview.png' },
    {index: 57, nombre: 'Cachamate coco', marca: 'Cachamate', tipo: 'Saborizante', tipoMolienda: 'Con palo', imagen: 'cachamateCoco-removebg-preview.png' },
    {index: 58, nombre: 'Cachamate hierbas litoral', marca: 'Cachamate', tipo: 'Hierbas', tipoMolienda: 'Con palo', imagen: 'cachamateHierbasLitoral-removebg-preview.png' },
    {index: 59, nombre: 'Cachamate naranja', marca: 'Cachamate', tipo: 'Saborizante', tipoMolienda: 'Con palo', imagen: 'cachamateNaranja-removebg-preview.png' },
    ] 
    return ContenedorYerbas
}  
export default TablaYerbas;