function CatalogoYerbas() {
    const ContenedorYerbas = [
    {index: 1, nombre: 'Canarias tradicional', marca: 'Canarias', tipo: 'tradicional', tipoMolienda: 'sin palo', imagen: 'public/imagenes/canarias.jfif' },
    {index: 2, nombre: 'Baldo tradicional', marca: 'Baldo', tipo: 'tradicional', tipoMolienda: 'sin palo', imagen: 'public/imagenes/baldo.jpg' },
    {index: 3, nombre: 'Canarias especial', marca: 'Canarias', tipo: 'especial', tipoMolienda: 'sin palo', imagen: 'public/imagenes/canariasEspecial.jpg' },
    {index: 4, nombre: 'Canarias serena', marca: 'Canarias', tipo: 'hierbas', tipoMolienda: 'sin palo', imagen: 'public/imagenes/canariasSerena.jpg' },
    {index: 5, nombre: 'Canarias te rojo y centella', marca: 'Canarias', tipo: 'hierbas', tipoMolienda: 'sin palo', imagen: 'public/imagenes/canariasTeRojoCentella.jpg' },
    {index: 6, nombre: 'Contigo tradicional', marca: 'Contigo', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/contigo.jpg' },
    {index: 7, nombre: 'contigo con hierbas', marca: 'Contigo', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/contigoConHierbas.jpg' },
    {index: 8, nombre: 'La Merced de monte', marca: 'La Merced', tipo: 'monte', tipoMolienda: 'con palo', imagen: 'public/imagenes/mercedDeMonte.webp' },
    {index: 9, nombre: 'Union tradicional', marca: 'Union', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/unionOriginal.webp' },
    {index: 10, nombre: 'Playadito hierbas', marca: 'Playadito', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/playaditoHierbas.webp' },
    {index: 11, nombre: 'Andresito tradicional', marca: 'Adresito', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/andresito.webp' },
    {index: 12, nombre: 'Kalena despalada', marca: 'Kalena', tipo: 'despalada', tipoMolienda: 'sin palo', imagen: 'public/imagenes/kalenaDespalada.webp' },
    {index: 13, nombre: 'La Merced campo y monte', marca: 'La Merced', tipo: 'campo y monte', tipoMolienda: 'con palo', imagen: 'public/imagenes/mercedCampoMonte.webp' },
    {index: 14, nombre: 'Titrayju tradicional', tipo: 'tradicional', marca: 'Titrayju', tipoMolienda: 'con palo', imagen: 'public/imagenes/titrayju.webp' },
    {index: 15, nombre: 'La Tranquera seleccion especial', marca: 'La Tranquera', tipo: 'especial', tipoMolienda: 'con palo', imagen: 'public/imagenes/tranqueraSeleccionEspecial.webp' },
    {index: 16, nombre: 'Nobleza gaucha seleccion especial', marca: 'Nombleza gaucha', tipo: 'especial', tipoMolienda: 'con palo', imagen: 'public/imagenes/noblezaGauchaSeleccion.webp' },
    {index: 17, nombre: 'Amanda seleccion especial', marca: 'Amanda', tipo: 'especial', tipoMolienda: 'con palo', imagen: 'public/imagenes/amandaEspecial.webp' },
    {index: 18, nombre: 'Taragui despalada', marca: 'Taragui', tipo: 'despalada', tipoMolienda: 'sin palo', imagen: 'public/imagenes/taraguiDespalada.webp' },
    {index: 19, nombre: 'Rosa monte seleccion especial', marca: 'Rosa monte', tipo: 'especial', tipoMolienda: 'con palo', imagen: 'public/imagenes/rosaMonteSeleccion.webp' },
    {index: 20, nombre: 'Cruz de malta seleccion especial', marca: 'Cruz de malta', tipo: 'especial', tipoMolienda: 'con palo', imagen: 'public/imagenes/cruzDeMaltaSeleccion.webp' },
    {index: 21, nombre: 'La Merced barbacua', marca: 'La Merced', tipo: 'barbacua', tipoMolienda: 'con palo', imagen: 'public/imagenes/mercedBarbacua.webp' },
    {index: 22, nombre: 'Amanda tradicional', marca: 'Amanda', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/amanda.webp' },
    {index: 23, nombre: 'Amanda premium', marca: 'Amanda', tipo: 'premium', tipoMolienda: 'con palo', imagen: 'public/imagenes/amandaPremium.webp' },
    {index: 24, nombre: 'Porongo tradicional', marca: 'Porongo', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/porongo.webp' },
    {index: 25, nombre: 'Playadito despalada', marca: 'Playadito', tipo: 'despalada', tipoMolienda: 'sin palo', imagen: 'public/imagenes/playaditoDespalada.webp' },
    {index: 26, nombre: 'Playadito tradicional', marca: 'Playadito', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/playadito.webp' },
    {index: 27, nombre: 'Nobleza gaucha suave', marca: 'Nobleza gaucha', tipo: 'suave', tipoMolienda: 'con palo', imagen: 'public/imagenes/noblezaGauchaSuave.webp' },
    {index: 28, nombre: 'Romance seleccion especial', marca: 'Romance', tipo: 'especial', tipoMolienda: 'con palo', imagen: 'public/imagenes/romanceSeleccion.webp' },
    {index: 29, nombre: 'Amanda naranja', marca: 'Amanda', tipo: 'saborizantes', tipoMolienda: 'con palo', imagen: 'public/imagenes/amandaNaranja.webp' },
    {index: 30, nombre: 'Amanda hierbas', marca: 'Amanda', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/amandaHierbas.webp' },
    {index: 31, nombre: 'La Merced campo', marca: 'La Merced', tipo: 'campo', tipoMolienda: 'con palo', imagen: 'public/imagenes/mercedCampo.webp' },
    {index: 32, nombre: 'Mañanita tradicional', marca: 'Mañanita', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/mañanita.webp' },
    {index: 33, nombre: 'Aguantadora tradicional', marca: 'Aguantadora', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/aguantadora.webp' },
    {index: 34, nombre: 'Amanda limon', marca: 'Amanda', tipo: 'saborizante', tipoMolienda: 'con palo', imagen: 'public/imagenes/amandaLimon.webp' },
    {index: 35, nombre: 'Amanda despalada', marca: 'Amanda', tipo: 'despalada', tipoMolienda: 'sin palo', imagen: 'public/imagenes/amandaDespalada.webp' },
    {index: 36, nombre: 'Kalena tradicional', marca: 'Kalena', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/kalena.webp' },
    {index: 37, nombre: 'Cruz de malta tradicional', marca: 'Cruz de malta', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/cruzDeMalta.webp' },
    {index: 38, nombre: 'Amanda hierbas serranas', marca: 'Amanda', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/amandaHierbasSerranas.webp' },
    {index: 39, nombre: 'Taragui tradicional', marca: 'Taragui', tipo: 'despalada', tipoMolienda: 'con palo', imagen: 'public/imagenes/taragui.webp' },
    {index: 40, nombre: 'Aguantadora suave', marca: 'Aguantadora', tipo: 'suave', tipoMolienda: 'con palo', imagen: 'public/imagenes/aguantadoraSuave.webp' },
    {index: 41, nombre: 'Rosa monte tradicional', marca: 'Rosa monte', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/rosaMonte.jpg' },
    {index: 42, nombre: 'Rosa monte despalada', marca: 'Rosa monte', tipo: 'despalada', tipoMolienda: 'sin palo', imagen: 'public/imagenes/rosaMonteDespalada.webp' },
    {index: 43, nombre: 'Pipore tradicional', marca: 'Pipore', tipo: 'tradicional', tipoMolienda: 'con palo', imagen: 'public/imagenes/pipore.webp' },
    {index: 44, nombre: 'Pipore suave', marca: 'Pipore', tipo: 'suave', tipoMolienda: 'con palo', imagen: 'public/imagenes/piporeSuave.webp' },
    {index: 45, nombre: 'Pipore despalada', marca: 'Pipore', tipo: 'despalada', tipoMolienda: 'sin palo', imagen: 'public/imagenes/piporeDespalada.jpg' },
    {index: 46, nombre: 'CBSE naranja', marca: 'CBSE', tipo: 'saborizante', tipoMolienda: 'con palo', imagen: 'public/imagenes/cbseNaranja.webp' },
    {index: 47, nombre: 'CBSE hierbas serranas', marca: 'CBSE', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/cbseHierbasSerranas.webp' },
    {index: 48, nombre: 'CBSE hierbas litoral', marca: 'CBSE', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/cbseHierbasLitoral.webp' },
    {index: 49, nombre: 'CBSE endulife', marca: 'CBSE', tipo: 'saborizante', tipoMolienda: 'con palo', imagen: 'public/imagenes/cbseEndulife.webp' },
    {index: 50, nombre: 'CBSE pomelo', marca: 'CBSE', tipo: 'saborizante', tipoMolienda: 'con palo', imagen: 'public/imagenes/cbsePomelo.webp' },
    {index: 51, nombre: 'CBSE frutos del bosque', marca: 'CBSE', tipo: 'saborizante', tipoMolienda: 'con palo', imagen: 'public/imagenes/cbseFrutosDelBosque.webp' },
    {index: 52, nombre: 'CBSE limon', marca: 'CBSE', tipo: 'saborizante', tipoMolienda: 'con palo', imagen: 'public/imagenes/cbseLimon.webp' },
    {index: 53, nombre: 'CBSE guarana', marca: 'CBSE', tipo: 'saborizante', tipoMolienda: 'con palo', imagen: 'public/imagenes/cbseGuarana.webp' },
    {index: 54, nombre: 'Cachamate hierbas', marca: 'Cachamate', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/cachamateHierbas.webp' },
    {index: 55, nombre: 'Cachamate hierbas digestivas', marca: 'Cachamate', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/cachamateHierbasDigestivas.jpg' },
    {index: 56, nombre: 'Cachamate hierbas pampeanas', marca: 'Cachamate', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/cachamateHierbasPampeanas.webp' },
    {index: 57, nombre: 'Cachamate coco', marca: 'Cachamate', tipo: 'saborizante', tipoMolienda: 'con palo', imagen: 'public/imagenes/cachamateCoco.png' },
    {index: 58, nombre: 'Cachamate hierbas litoral', marca: 'Cachamate', tipo: 'hierbas', tipoMolienda: 'con palo', imagen: 'public/imagenes/cachamateHierbasLitoral.png' },
    {index: 59, nombre: 'Cachamate naranja', marca: 'Cachamate', tipo: 'saborizante', tipoMolienda: 'con palo', imagen: 'public/imagenes/cachamateNaranja.jpg' },
    ] 
    return ContenedorYerbas
}  
export default CatalogoYerbas;